#!/bin/sh

state=$(amixer | awk '{ if (NR==5) print $6 }')

if [ $state == '[off]' ]
then
  echo ''
else
  volume=$(amixer | awk '{ if (NR==5) print substr($4, 2, length($4) - 2) }')
  echo -n ''; echo ' '$volume
fi
