#!/bin/sh

state=$(amixer | awk '{ if (NR==5) print $6 }')

if [ $state == '[off]' ]
then
  echo '婢'
else
  volume=$(amixer | awk '{ if (NR==5) print substr($4, 2, length($4) - 2) }')
  case $volume in
    100)
      icon="墳"
      ;;
    [0-9])
      icon="奄"
      ;;
    [1-6]*)
      icon="奔"
      ;;
    *)
      icon="墳"
      ;;
  esac
  echo -n $icon
fi
